minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true # no git branch as package url
minimumReleaseAgeExclude:
  - "@vitejs/plugin-react@6.0.2"
  - "typescript@7.0.2" # used by tsc
  - "@typescript/typescript6@6.0.2" # used when importing typescript in scripts/modules and used by tsc6
  - "@typescript/typescript-*"
resolutionMode: highest

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
