allowBuilds:
  unrs-resolver: true # used by eslint-import-resolver-typescript and eslint-config-airbnb-extended
minimumReleaseAge: 10080 # 7 days
blockExoticSubdeps: true # no git branch as package url
minimumReleaseAgeExclude:
  - '@vitejs/plugin-react@6.0.2'
resolutionMode: highest

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
    - win32
