export const START_GAME = 'START_GAME';
export const PAUSE_GAME = 'PAUSE_GAME';
export const RESET_GAME = 'RESET_GAME';

export const TRIGGER_COLLISION = 'TRIGGER_COLLISION';
export const TRIGGER_COLLISION_END = 'TRIGGER_COLLISION_END';
export const TOGGLE_PLAY_STATE = 'TOGGLE_PLAY_STATE';
export const TOGGLE_SOUND = 'TOGGLE_SOUND';
export const SET_LAST_POSITION = 'SET_LAST_POSITION';
