export const START_GAME = 'START_GAME';
export const RESET_GAME = 'RESET_GAME';

export const TRIGGER_COLLISION = 'TRIGGER_COLLISION';
export const TOGGLE_PLAY_STATE = 'TOGGLE_PLAY_STATE';
export const TOGGLE_SOUND = 'TOGGLE_SOUND';
